### ISSUE TITLE
非常了不起的仓库

### ISSUE THREAD

**Issue by dsp6414** [zqlovejyc/ZqUtils.Core#1]
代码质量很好也很有帮助，就是支持包太多。如果能裁剪发行只依赖NetCore或Net standard.则应用场景会更多，否则发行包太大效果适得其反。

**Comment by zqlovejyc** [comment]
> 代码质量很好也很有帮助，就是支持包太多。如果能裁剪发行只依赖NetCore或Net standard.则应用场景会更多，否则发行包太大效果适得其反。

目前暂未考虑拆分开发行，后续会考虑考虑。

**Comment by dsp6414** [comment]
已收到！
